### PR TITLE
jobs/rootfs-trigger: pass KCI_CORE_[URL|BRANCH]

### PR DESCRIPTION
**Pull request by khilman**
Signed-off-by: Kevin Hilman <khilman@baylibre.com>

### CODE REVIEW

**Comment by khilman** [comment]
Untested, but should address: https://github.com/kernelci/kernelci-jenkins/issues/29

**Comment by gctucker** [comment]
Please add a message in the commit explaining why this is needed.

**Comment by khilman** [comment]
Updated with description in commit log.

**Comment by gctucker** [comment]
OK thanks - this will matter when we start using settings files, as we could keep the parameters to override things on a per-build basis.

**Comment by gctucker** [comment]
Thanks!

**Pull request merged**
