### PR TITLE
kernel-arch-complete.sh: Remove stable tree maillist

### PR DESCRIPTION
**Pull request by nuclearcat**
we are disabling automated reports, but we will
keep reviewing reports manually and will report
to stable tree about new issues.
Also we will enable reports from new API/Pipeline in near future.

### CODE REVIEW

**Comment by gctucker** [comment]
Why disable the reports?  Has this been discussed on the stable mailing list?  It has proved to be useful in the past.

**Comment by nuclearcat** [comment]
Yes, it was discussed on maillist: https://lore.kernel.org/stable/738c6c87-527e-a1c2-671f-eed6a1dbaef3@collabora.com/T/#u and per follow up email we are removing automated report and will start (at least for now) manual reviews.

**Comment by gctucker** [comment]
Yes I've read this email thread, and I don't think it means the automated reports should stop.  It just means Greg doesn't seem to be reading them, which isn't new as they're full of noise.  But others might depend on them.  I've pinged Sasha on IRC as I know he used to read them for stable-rc and probably still does.

**Comment by nuclearcat** [comment]
Based on IRC discussion as i understand Sasha prefer better reports too.

**Comment by gctucker** [comment]
@nuclearcat That's not true:

```
sashal_> 14:03:43> My read of the pull request is that this will get replaced with better signal, but yes - I wouldn't disable the automated reports until something like that is in place
```

As discussed on the mailing list, maybe others still rely on this report and at least sending a warning email about the intention to stop them would be the least we can do to communicate the change with the community.

**Pull request merged**
