### PR TITLE
CHROMEOS build.jpl: Use chromeos.kernelci.org branch of jenkins library

### PR DESCRIPTION
**Pull request by nuclearcat**
As ChromeOS jobs are a bit different, we need to use also different branch of Jenkins libary.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
I thought it would work if you just defined the library branch in Jenkins?

This patch is a bit risky as if it gets merged on the `main` branch it would break all the other builds.

**Comment by nuclearcat** [comment]
I tried to define pipeline libraries on folder, but this settings are getting erased on each staging redeploy.
I think i can use WORKSPACE variable in Jenkins and extract job path, where if i detect chromeos folder, i define library for chromeos branch, otherwise as default. Probably this approach is safer?

**Comment by gctucker** [comment]
Ah OK, I thought the `chromeos` folder was not set up by the config-as-code stuff and it would just persist any manual setup.  OK then this patch is probably the next best solution.  Maybe add a comment in `build.jpl` to say this is explicitly for `chromeos.kernelci.org` jobs and it should not be merged in the main branch.

**Comment by nuclearcat** [comment]
It worked, but i need to put some conditions (use @chromeos.kernelci.org only in folder chromeos), so it can work in main branch, in case it is merged
```
Loading library kernelci@chromeos.kernelci.org
Attempting to resolve chromeos.kernelci.org from remote references...
 > git --version # timeout=10
 > git --version # 'git version 2.11.0'
 > git ls-remote -- https://github.com/kernelci/kernelci-jenkins # timeout=10
Found match: refs/heads/chromeos.kernelci.org revision 8a41cc4073b38f30da12cc7203a68daf40a7c3c4
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/chromeos/kernel-build__libs/kernelci__4/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kernelci/kernelci-jenkins # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kernelci/kernelci-jenkins
 > git --version # timeout=10
 > git --version # 'git version 2.11.0'
 > git fetch --no-tags --progress -- https://github.com/kernelci/kernelci-jenkins +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision 8a41cc4073b38f30da12cc7203a68daf40a7c3c4 (chromeos.kernelci.org)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8a41cc4073b38f30da12cc7203a68daf40a7c3c4 # timeout=10
Commit message: "CHROMEOS only send emails for kernelci tree"
 > git rev-list --no-walk b53a530b49d9649fbc0e41d7fdd81abed9ffdd6f # timeout=10
```

**Comment by gctucker** [comment]
We can just not merge it, right?  I don't think it would get merged by accident.

Also I still don't get why any changes to the `chromeos` folder would get undone as this is not managed by the CasC stuff.  I have done this for my personal folder and it's persistent:
https://bot.staging.kernelci.org/job/gtucker/configure

**Comment by nuclearcat** [comment]
It is managed by CasC, while your folder is not.
0004-STAGING-jobs.groovy-add-chromeos-jobs.patch
```
From 28241cd7df7e252699527afda90b1d87a44e2933 Mon Sep 17 00:00:00 2001
From: Guillaume Tucker <guillaume.tucker@collabora.com>
Date: Wed, 2 Mar 2022 20:25:29 +0000
Subject: [PATCH 4/4] STAGING jobs.groovy: add chromeos jobs

---
 jobs.groovy | 81 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 81 insertions(+)

diff --git a/jobs.groovy b/jobs.groovy
index eb9fc6c4c94e..2f306eaa4acf 100644
--- a/jobs.groovy
+++ b/jobs.groovy
@@ -339,3 +339,84 @@ pipelineJob('lava-bisection') {
     stringParam('DOCKER_BASE', KCI_DOCKER_BASE, 'Dockerhub base address used for the build images.')
   }
 }
+
+/* Chrome OS jobs */
+
+folder('chromeos') {
+    displayName('chromeos')
+    description('Jobs for chromeos.kernelci.org')
+}
+
+pipelineJob('chromeos/kernel-tree-monitor') {
+  definition {
```

**Comment by gctucker** [comment]
Ah great, now that make sense.  So that's the place where the library can be defined properly too.

**Comment by nuclearcat** [comment]
Patch should not be required anymore

**Comment by nuclearcat** [comment]
Reopened as PR still required

**Comment by nuclearcat** [comment]
Not required anymore, it was temporary workaround

**Pull request closed without merging**
