### PR TITLE
kernel-arch-complete.sh: Update email address for CIP notifications

### PR DESCRIPTION
**Pull request by patersonc**
CIP would like to move the KernelCI email notifications over to the cip-testing-results mailing list.

### CODE REVIEW

**Comment by patersonc** [comment]
It would be good to be able to test this change before it is merged, as I need to make sure that the emails from the KernelCI bot can get through without manual moderation. If they cannot, I may need to get a special target email address configured as we had before for the cip-dev mailing list.

**Comment by nuclearcat** [comment]
I think it is a bit difficult to get staging send email to regular targets. 
I suggest we can try following: we can do usual monday production update, i will notify in Slack on completion, theb if everything will work as should - you confirm, and we keep it, if not, i can quickly reverse or update address - and do partial production update again.
Is it ok like this?

**Comment by patersonc** [comment]
> I think it is a bit difficult to get staging send email to regular targets. I suggest we can try following: we can do usual monday production update, i will notify in Slack on completion, theb if everything will work as should - you confirm, and we keep it, if not, i can quickly reverse or update address - and do partial production update again. Is it ok like this?

That's fine with me.

If it's easier, we can just merge the change. If it needs changing again then I'll create a new MR. CIP can live without the emails for a little while if needed.

**Comment by nuclearcat** [comment]
Ok merging and i will try to check after production update at monday if there is any errors or issues.

**Comment by patersonc** [comment]
Hello

I'm still seeing emails sent to the old mailing list. Has this MR been pushed to production?

Thanks

**Comment by nuclearcat** [comment]
I will update it manually today, i forgot that legacy system doesn't update jenkins properly.

**Pull request merged**
