### PR TITLE
jobs/bisect.jpl: drop kernelci-core git clone

### PR DESCRIPTION
**Pull request by gctucker**
Stop cloning kernelci-core as it's already present in the new Docker images.  Update all instances where this was used to simplify the code.

Signed-off-by: Guillaume Tucker <guillaume.tucker@collabora.com>

### CODE REVIEW

**Comment by gctucker** [comment]
Testing on staging by resubmitting a job that worked previously:
https://bot.staging.kernelci.org/job/lava-bisection/10801/console

(The "revert" check failed at the end of the bisection so it's a false-positive, but the logic worked fine).

**Review by nuclearcat — APPROVED** [review]
LGTM, as it's tested

**Comment by gctucker** [comment]
> LGTM, as it's tested

Well it's a bit early to tell, the staging job might take hours to complete.  Please come back when this PR is marked as "ready for review" ;)

**Comment by gctucker** [comment]
The "good revision" check failed, so I think that's not enough to check the whole job is working as expected.  I'll artificially create a regression on a branch for that to really test it (also it will be faster with just a handful of commits to bisect).

**Comment by gctucker** [comment]
Small update: I've run some jobs that caused a regression, then the bisections were "started" according to the backend logs but there's nothing in Jenkins:
```
Sep 21 16:40:56 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Saving 'test' report for 'gtucker-kernelci-staging-kernelci-bisect-snapshot-025-9-g21083a13f5c4'
Sep 21 16:40:56 kernelci-staging kernelci-celery[26535]: [    INFO/MainThread] Received task: trigger-test-bisections[2fbe8582-801d-44b1-8a19-3fa4a8a0d2c6]
Sep 21 16:40:56 kernelci-staging kernelci-celery[26535]: [    INFO/MainThread] Scaling up 1 processes.
Sep 21 16:40:56 kernelci-staging kernelci-celery[26535]: [ WARNING/MainThread] QoS: Disabled: prefetch_count exceeds 65535
Sep 21 16:40:56 kernelci-staging kernelci-celery[26535]: [    INFO/MainThread] Task send-test-report[88b23d3d-5dcd-4e8b-8543-b44f39addf84] succeeded in 1.17809231021s: 'SENT'
Sep 21 16:40:56 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Triggering bisections for 'gtucker-kernelci-staging-kernelci-bisect-snapshot-025-9-g21083a13f5c4-baseline'
Sep 21 16:40:56 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Triggering bisection for gtucker/kernelci-staging: baseline.dmesg.emerg on mt8173-elm-hana in lab-collabora
Sep 21 16:40:57 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Triggering bisection for gtucker/kernelci-staging: baseline.dmesg.emerg on mt8173-elm-hana in lab-collabora
Sep 21 16:40:57 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Triggering bisection for gtucker/kernelci-staging: baseline.login on hp-x360-14-G1-sona in lab-collabora
Sep 21 16:40:57 kernelci-staging kernelci-celery[56186]: [    INFO/MainThread] Triggering bisection for gtucker/kernelci-staging: baseline.login on qemu_arm64-virt-gicv3 in lab-collabora-staging
Sep 21 16:40:57 kernelci-staging kernelci-celery[26535]: [    INFO/MainThread] Task trigger-test-bisections[2fbe8582-801d-44b1-8a19-3fa4a8a0d2c6] succeeded in 0.714343746193s: None
```

**Comment by gctucker** [comment]
Ah, the `gtucker` tree is not on the list of trees to bisect:
https://bot.staging.kernelci.org/job/lava-bisection/11003/console

Resubmitting bisection jobs now...

**Comment by gctucker** [comment]
Next step, this script is missing:
```
./scripts/lava-v2-callback.py: not found
```
https://bot.staging.kernelci.org/job/lava-bisection/11005/console

Probably it should be moved to kernelci-jenkins in the scripts directory.

**Comment by gctucker** [comment]
Tested OK on staging: https://bot.staging.kernelci.org/job/gtucker/job/lava-bisection/52/consoleFull

In coordination with https://github.com/kernelci/kernelci-core/pull/1449

**Comment by gctucker** [comment]
OK merging now, if any issue pops up that can be addressed next week.

**Pull request merged**
