### PR TITLE
Move jpl files from kernelci-core/jenkins

### PR DESCRIPTION
**Pull request by Lakshmipathi**
Move build, build-trigger, bisect, monitor and test-runner jpl files
from kernelci-core and update jobs.groovy.

Signed-off-by: Lakshmipathi <lakshmipathi.ganapathi@collabora.com>

### CODE REVIEW

**Comment by Lakshmipathi** [comment]
okay will check @gctucker

**Comment by gctucker** [comment]
Tested OK on staging: https://staging.kernelci.org/build/kernelci/branch/staging.kernelci.org/kernel/staging-20200706.2/

**Comment by gctucker** [comment]
Bisection job also tested OK on staging: https://bot.staging.kernelci.org/job/lava-bisection/784/consoleFull

**Comment by gctucker** [comment]
OK this is ready now, thanks.  Please create a follow-up PR to add the library files (essentially `Job.groovy`).  The git URL and branch where Jenkins gets the library sources from are set in `config/jenkins.yaml` since it's a system-wide setting.

**Pull request merged**
